name: CI

on:
  pull_request:
  push:
    branches: ['main']

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      PUSH: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      TEST_TAG: docker.samsarabarandgrill.com/yourself/weather-proxy:test
      LATEST_TAG: docker.samsarabarandgrill.com/yourself/weather-proxylatest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - run: pnpm i

      - name: Login to registry
        uses: docker/login-action@v2
        with:
          registry: docker.samsarabarandgrill.com
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and export
        uses: docker/build-push-action@v4
        with:
          context: .
          load: true
          tags: ${{ env.TEST_TAG }}

      - name: Build and push
        uses: docker/build-push-action@v4
        if: ${{ env.PUSH }}
        with:
          context: .
          push: ${{ env.PUSH }}
          tags: ${{ env.LATEST_TAG }}
